services:
  # Backend API (Python + OpenCV + OMR)
  - type: web
    name: lerprova-api-app
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: API_KEY_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./lerprova_server.db

  # Frontend (React + Vite)
  - type: web
    name: lerprova-frontend-app
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm install @rollup/rollup-linux-x64-gnu && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: lerprova-api-app
          type: web
          property: host
